### ISSUE TITLE
Bilder für die Doku hochladen

### ISSUE THREAD

**Issue by Linthel** [gitdanny0001/dasLabyrinthdesGruselns#1]
![mauern](https://user-images.githubusercontent.com/40355411/47356881-9b777a00-d6c5-11e8-9f2b-97c936f151a2.jpg)

**Comment by Linthel** [comment]
![mindmap](https://user-images.githubusercontent.com/40355411/47388969-d0aab900-d713-11e8-88d2-699475847d3a.jpg)

**Comment by Linthel** [comment]
![kernprinzip](https://user-images.githubusercontent.com/40355411/47389284-ac9ba780-d714-11e8-8010-6b56de6fba06.png)

**Comment by Linthel** [comment]
![bartle model](https://user-images.githubusercontent.com/40355411/47389675-afe36300-d715-11e8-813c-73623ea34532.png)

**Comment by Linthel** [comment]
![d v l](https://user-images.githubusercontent.com/40355411/47449166-453c3100-d7c2-11e8-8999-fd45a416d345.jpg)

**Comment by Linthel** [comment]
![pbs](https://user-images.githubusercontent.com/40355411/47453191-6a35a180-d7cc-11e8-8156-b94ef11fb898.jpg)

**Comment by Linthel** [comment]
![pbs](https://user-images.githubusercontent.com/40355411/47453310-b1bc2d80-d7cc-11e8-8882-f8f3c6b5aea0.jpg)

**Comment by Linthel** [comment]
![wbs](https://user-images.githubusercontent.com/40355411/47453596-6fdfb700-d7cd-11e8-887a-f1d46cdbb198.jpg)

**Comment by Linthel** [comment]
Alle Bilder Lokal noch vorhanden

**Comment by WilliGerner** [comment]
![verrucktelabyrinth](https://user-images.githubusercontent.com/40355370/47551134-aa4a7080-d901-11e8-9c70-1d985a7eba68.jpg)

**Comment by WilliGerner** [comment]
![verruckteslabyrinth brettversion](https://user-images.githubusercontent.com/40355370/47551151-b46c6f00-d901-11e8-9e43-c7029cc51bb0.jpg)

**Comment by Linthel** [comment]
![das labyrinth des gruselns mindmap](https://user-images.githubusercontent.com/40355411/47557192-5dba6180-d910-11e8-94c7-7c0653f55ef7.png)

**Comment by Linthel** [comment]
![das verruckte labyrinth mindmap](https://user-images.githubusercontent.com/40355411/47557207-66ab3300-d910-11e8-985c-f5fad9ffc5db.png)

**Comment by gitdanny0001** [comment]
![mindmap_digital v1](https://user-images.githubusercontent.com/38943889/47557217-69a62380-d910-11e8-8ad5-d6dd71bb6d9c.png)

v1(digital)

**Comment by gitdanny0001** [comment]
![spierlsicht_1](https://user-images.githubusercontent.com/38943889/47557250-7dea2080-d910-11e8-9d4e-fd99a1d20086.png)
v1(brettspiel

**Comment by WilliGerner** [comment]
![verrucktelabyrinth mindmap pc](https://user-images.githubusercontent.com/40355370/47566628-9a945180-d92c-11e8-86ed-8329f44b6fa0.jpg)

**Comment by WilliGerner** [comment]
![verruckteslabyrinth brettversion _2](https://user-images.githubusercontent.com/40355370/47566641-9ff19c00-d92c-11e8-995c-9950d1d0f0ed.jpg)

**Comment by gitdanny0001** [comment]
![analog](https://user-images.githubusercontent.com/38943889/47566746-e8a95500-d92c-11e8-9713-3656011c9a03.png)
![digital](https://user-images.githubusercontent.com/38943889/47566747-e8a95500-d92c-11e8-9e9d-99eb8290e78a.png)

**Comment by Linthel** [comment]
![persona mannlich](https://user-images.githubusercontent.com/40355411/47672418-3d113680-dbb2-11e8-9d07-c7ee97c28d06.PNG)

https://www.google.de/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiBrJuOpazeAhUB_qQKHcABAfwQjRx6BAgBEAU&url=https%3A%2F%2Fde.vecteezy.com%2Fvektorkunst%2F133402-personas-vektor&psig=AOvVaw3-LSV0WSOhvi4ONhps1qjG&ust=1540924464035465 (29.10.2018, 19:39)


![persona weiblich](https://user-images.githubusercontent.com/40355411/47672422-3edafa00-dbb2-11e8-88b4-2560d50be7d5.PNG)

https://de.vecteezy.com/vektorkunst/132809-personas-icon-set-freier-vektor (29.10.2018, 19:39)

**Comment by gitdanny0001** [comment]
![kobbert](https://user-images.githubusercontent.com/38943889/48551325-7eedec80-e8d5-11e8-901c-b58a2739e6db.jpg)

**Comment by gitdanny0001** [comment]
![kobbert_2](https://user-images.githubusercontent.com/38943889/48551611-4b5f9200-e8d6-11e8-9d28-159990bf9e06.jpg)

**Comment by gitdanny0001** [comment]
![bild_1](https://user-images.githubusercontent.com/38943889/48553936-49e59800-e8dd-11e8-8881-db98fefa088f.png)
![bild_2](https://user-images.githubusercontent.com/38943889/48553938-49e59800-e8dd-11e8-975e-0eebd627ad10.png)
