### ISSUE TITLE
Änderungen die im Wiki gemacht wurden 

### ISSUE THREAD

**Issue by Linthel** [gitdanny0001/dasLabyrinthdesGruselns#2]

**Comment by WilliGerner** [comment]
* Aufgaben Liste aktualisiert.

* Bild im Wiki bei der Essenz/ Core Gameplay bearbeitet.   ( Wegfindung statt Weg bauen)

* Bild im Wiki bei Feature Set bearbeitet.  ( Wegfindung statt Weg bauen)

*Fragen Katalog erweitert.

**Comment by WilliGerner** [comment]
2 Bilder zur Mindmap(Gameplay) hochgeladen.
